# Generated by Django 5.1.5 on 2025-02-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_issue_options_audit_trail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit_trail',
            options={'ordering': ['updated_at', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['updated_at', 'created_at']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year_of_study',
            field=models.IntegerField(null=True),
        ),
    ]
