# Generated by Django 5.1.5 on 2025-02-03 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_audit_trail_options_alter_issue_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='course_code',
            new_name='course_unit_code',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='course_name',
            new_name='course_unit_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='year_of_study',
        ),
    ]
