[phases.setup]
nixPkgs = ["python310", "pip", "postgresql"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmds = ["python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"]
